---

- name: install go
  homebrew: name=go state=present

- name: install gofmt
  command: go get -u {{item}}
  environment:
    GOPATH: "{{ lookup('env','HOME') }}/Code/go"
  with_items:
    - golang.org/x/tools/cmd/goimports
    - golang.org/x/tools/cmd/vet
    - golang.org/x/tools/cmd/oracle
    - golang.org/x/tools/cmd/godoc
