---

- name: install go
  homebrew: name=go state=present

- name: install gofmt
  command: go get {{item}}
  environment:
    GOPATH: "{{ lookup('env','HOME') }}/Code/go"
  with_items:
    - golang.org/x/tools/cmd/goimports
    - golang.org/x/tools/cmd/vet
    - golang.org/x/tools/cmd/oracle
    - golang.org/x/tools/cmd/godoc
    - github.com/golang/lint/golint
    - github.com/nsf/gocode
    - golang.org/x/tools/cmd/gorename

- name: ensure presence of bash_profile
  file: state=touch path={{home_directory}}/.bash_profile

- name: add GOPATH to bash_profile
  lineinfile: dest=~/.bash_profile regexp="^export GOPATH=$HOME\/Code\/go" line="export GOPATH=$HOME/Code/go"
