---

- name: install cask applications for all users
  homebrew_cask: name={{item}} state=present
  with_items:
    - slack
    - dropbox
    - keepingyouawake
    - 1password
    - google-chrome

- name: place the aliases configuration file
  become: yes
  copy:
    src: "bashrc.aliases.sh"
    dest: "/etc/bashrc.aliases.sh"
    owner: root
    group: wheel
    mode: 0644

- name: add the aliases configuration files to bashrc
  become: yes
  lineinfile: >
    dest=/etc/bashrc
    regexp="bashrc.aliases.sh"
    line="if [ -f /etc/bashrc.aliases.sh ]; then . /etc/bashrc.aliases.sh; fi"
    state=present
    create=true
