---

- name: tap caskroom/versions
  homebrew_tap: tap=caskroom/versions state=present

- name: install developer brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - wget
    - apg
    - htop-osx
    - watch
    - rsync
    - git-flow
    - hub
    - ack
    - awscli

- name: install developer cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - imageoptim
    - sequel-pro
    - java6
    - java
    - atom
